### PR TITLE
Catch bad status line errors.

### PR DESCRIPTION
**Pull request by boltgolt**
Because of the overall instability of the API toonlib was throwing very long errors every once in awhile: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.homeassistant/deps/lib/python3.4/site-packages/toonlib/toonlib.py", line 293, in power
    power = self._state['powerUsage']
  File "/home/user/.homeassistant/deps/lib/python3.4/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/home/user/.homeassistant/deps/lib/python3.4/site-packages/toonlib/toonlib.py", line 178, in _state
    state.update(self._get_data('/client/auth/retrieveToonState'))
  File "/home/user/.homeassistant/deps/lib/python3.4/site-packages/toonlib/toonlib.py", line 195, in _get_data
    timeout=REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

This should catch this error (and other possible API issues) in a more elegant way.

### CODE REVIEW

**Comment by costastf** [comment]
Hi @Boltgolt ! Thanks for this. Have you tested this locally and it does it work as you would expect? It seems to me that you are handling the last exception and that would not really provide much value since the first two would still go on log.

**Comment by boltgolt** [comment]
If i recall correctly, all errors were catched but that might not have been the exact same exception, i'll let it pass the original error locally to check and i'll report back.

**Comment by costastf** [comment]
Awesome, thanks!

**Comment by boltgolt** [comment]
It catches it but then just prints the entire trace anyway, i'll have a look.

**Comment by costastf** [comment]
I have been getting consistent timeouts on the three minute barrier and have tried versions 0.57, .57.3, 0.58, 0.58.1 and 0.56 with the same result. I was also contacted by an engineer of Quby (the company that makes toon) and was pointed to the direction of their new api that requires registration and uses Oauth2. I have already created an account for me and will start looking into that as soon as possible. I think that, that is probably the way to go in the long run. I just thought I'd let you know. Have a great day!

**Comment by boltgolt** [comment]
It's great that quby reached out instead of filing a ToS complaint! Thanks for letting me know

**Comment by costastf** [comment]
Yeah, that was really cool of them. As soon as I start working on it I will let you know. I am hoping that I can make the new library exposing the same interface with the old one so at the end of the day we would just need to switch the requirement on ToonHA. Of course I still have no clue how the new api looks like so that is just wishful thinking. I will keep you up to date with new stuff.

**Comment by costastf** [comment]
I have completed the new library that works with the official api (https://github.com/costastf/toonapilib.git) and I think that for now we should focus development efforts on that. So closing this MR. Thanks though!

**Comment by boltgolt** [comment]
Great, thanks for implementing it! Adding a deprecation notice to the readme would be helpful for anyone finding this later on

**Comment by costastf** [comment]
Good point, I will add one tomorrow! How about you doing the component
part, are you up for it?

**Comment by boltgolt** [comment]
Yeah, i'll switch toonlib with toonapilib somewhere in the coming days. It's a bit busy so i don't know when _exactly_.

**Pull request closed without merging**
